// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGachaInfo(arg1, arg2) {
  return window['go']['main']['App']['GetGachaInfo'](arg1, arg2);
}

export function StartProxyServer() {
  return window['go']['main']['App']['StartProxyServer']();
}

export function StopProxyServer() {
  return window['go']['main']['App']['StopProxyServer']();
}

export function Sync() {
  return window['go']['main']['App']['Sync']();
}

export function Uids() {
  return window['go']['main']['App']['Uids']();
}
