// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOption() {
  return window['go']['main']['App']['GetOption']();
}

export function GetPieDatas() {
  return window['go']['main']['App']['GetPieDatas']();
}

export function GetUids() {
  return window['go']['main']['App']['GetUids']();
}

export function SaveOption(arg1) {
  return window['go']['main']['App']['SaveOption'](arg1);
}

export function Sync(arg1) {
  return window['go']['main']['App']['Sync'](arg1);
}
