// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOption():Promise<main.Option>;

export function GetPieDatas():Promise<void>;

export function GetUids():Promise<Array<string>>;

export function SaveOption(arg1:main.Option):Promise<void>;
