// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetOption():Promise<main.Option>;

export function GetPieDatas(arg1:string):Promise<main.GachaPieDate>;

export function GetUids():Promise<Array<string>>;

export function SaveOption(arg1:main.Option):Promise<void>;

export function Sync(arg1:boolean):Promise<string>;
