// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2, arg3, arg4);
}

export function GetNumWithLast(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNumWithLast'](arg1, arg2, arg3);
}

export function GetOption() {
  return window['go']['main']['App']['GetOption']();
}

export function GetPieDatas(arg1) {
  return window['go']['main']['App']['GetPieDatas'](arg1);
}

export function GetUids() {
  return window['go']['main']['App']['GetUids']();
}

export function SaveOption(arg1) {
  return window['go']['main']['App']['SaveOption'](arg1);
}

export function Sync(arg1) {
  return window['go']['main']['App']['Sync'](arg1);
}
