// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';

export function GetLogs(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<database.GachaLog>>;

export function GetNumWithLast(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetOption():Promise<main.Option>;

export function GetPieDatas(arg1:string):Promise<main.GachaPieDate>;

export function GetUids():Promise<Array<string>>;

export function SaveOption(arg1:main.Option):Promise<void>;

export function Sync(arg1:boolean):Promise<string>;
