// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMsg() {
  return window['go']['main']['Bridge']['GetMsg']();
}

export function PutMsg(arg1) {
  return window['go']['main']['Bridge']['PutMsg'](arg1);
}
